### PR TITLE
DLM-387 allow arbitrary subexpression bracketing

### PR DESCRIPTION
**Pull request by lawley**

### CODE REVIEW

**Comment by kaicode** [comment]
Hi @lawley, the file you have suggested changes to was actually generated from the ABNF provided by Linda. Your change looks sensible but I don't want it to lost when the file is regenerated. Do you happen to know if our ABNF file is out of date or if there has been any discussion in this area?

**Review by kaicode — CHANGES_REQUESTED** [review]
Looks like our ABNF file is up to date with the [latest](https://confluence.ihtsdotools.org/display/DOCSCG/5.1+Normative+Specification) apart from the `booleanValue` addition.
Could you ask Linda to make your suggested change in the upstream specification then I would be happy to pull that in and regenerate the Antlr file and parser.
This is a reference implementation so I really have to keep it in line with the spec. Sorry to be awkward! 😄

**Comment by lawley** [comment]
On reflection, this change is insufficient -- attributename needs to be updated, and expressionvalue should be focusconcept, not conceptreference.

**Comment by lawley** [comment]
Thanks Kai, I've opened a ticket on the spec which is where I presume the ABNF source if truth is.

Michael

Michael

________________________________

**Pull request closed without merging**
